version: "3"

services:
  web:
    build: ./app
    volumes:
      - ./app:/src/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
